name: Build and Publish DirectorySize

on:
  push:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: './csharp10'
      
    strategy:
      matrix:
        runtime: [win10-x64, osx.11.0-arm64, linux-x64]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build and Publish ${{ matrix.runtime }} runtime
      run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained --nologo -o publish -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
  
    - name: Compress binary
      run: |
        tar czvf directorysize.tar.gz publish/DirectorySize*
        ls -alh
        ls -alh directorysize.tar.gz 
        pwd

    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: directory-size/csharp10/directorysize.tar.gz
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
